name: jg_clusterless_decoding
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.6"
- loren_frank_data_processing
- ripple_detection
- replay_trajectory_classification
- trajectory_analysis_tools
- numpy
- scipy
- matplotlib
- xarray
- pandas
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip
- pip:
  - nb_black
